export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS';
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE';

export const SET_USER = 'SET_USER';
export const CLEAR_USER = 'CLEAR_USER';

export const DELETE_USER = 'DELETE_USER';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const GET_USERS_LIST = 'GET_USERS_LIST';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';
export const GET_USERS_LIST_FAILURE = 'GET_USERS_LIST_FAILURE';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const REQUEST_DELETE_ACCOUNT = 'REQUEST_DELETE_ACCOUNT';
export const REQUEST_DELETE_ACCOUNT_SUCCESS = 'REQUEST_DELETE_ACCOUNT_SUCCESS';
export const REQUEST_DELETE_ACCOUNT_FAILURE = 'REQUEST_DELETE_ACCOUNT_FAILURE';

export const ADD_FILM = 'ADD_FILM';
export const ADD_FILM_SUCCESS = 'ADD_FILM_SUCCESS';
export const ADD_FILM_FAILURE = 'ADD_FILM_FAILURE';

export const DELETE_FILM = 'DELETE_FILM';
export const DELETE_FILM_SUCCESS = 'DELETE_FILM_SUCCESS';
export const DELETE_FILM_FAILURE = 'DELETE_FILM_FAILURE';

export const GET_FILM_LIST = 'GET_FILM_LIST';
export const GET_FILM_LIST_SUCCESS = 'GET_FILM_LIST_SUCCESS';
export const GET_FILM_LIST_FAILURE = 'GET_FILM_LIST_FAILURE';

export const UPDATE_FILM = 'UPDATE_FILM';
export const UPDATE_FILM_SUCCESS = 'UPDATE_FILM_SUCCESS';
export const UPDATE_FILM_FAILURE = 'UPDATE_FILM_FAILURE';

export const BOOK_TICKET = 'BOOK_TICKET';
export const BOOK_TICKET_SUCCESS = 'BOOK_TICKET_SUCCESS';
export const BOOK_TICKET_FAILURE = 'BOOK_TICKET_FAILURE';

export const GET_TICKETS = 'GET_TICKETS';
export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS';
export const GET_TICKETS_FAILURE = 'GET_TICKETS_FAILURE';

export const DELETE_TICKETS = 'DELETE_TICKETS';
export const DELETE_TICKETS_SUCCESS = 'DELETE_TICKETS_SUCCESS';
export const DELETE_TICKETS_FAILURE = 'DELETE_TICKETS_FAILURE ';
