export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_USER_FAILURE";

export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const LOGOUT_USER = "LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAILURE = "LOGOUT_USER_FAILURE";

export const SET_USER = 'SET_USER';
export const DELETE_USER = 'DELETE_USER';

export const GET_USERS_LIST = 'GET_USERS_LIST';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';
export const GET_USERS_LIST_FAILURE = 'GET_USERS_LIST_FAILURE';

export const ADD_FILM = 'ADD_FILM';
export const ADD_FILM_SUCCESS = 'ADD_FILM_SUCCESS';
export const ADD_FILM_FAILURE = 'ADD_FILM_FAILURE';

export const DELETE_FILM = 'DELETE_FILM';
export const DELETE_FILM_SUCCESS = 'DELETE_FILM_SUCCESS';
export const DELETE_FILM_FAILURE = 'DELETE_FILM_FAILURE';

export const GET_FILM_LIST = 'GET_FILM_LIST';
export const GET_FILM_LIST_SUCCESS = 'GET_FILM_LIST_SUCCESS';
export const GET_FILM_LIST_FAILURE = 'GET_FILM_LIST_FAILURE';

export const BOOK_TICKET = 'BOOK_TICKET';
export const BOOK_TICKET_SUCCESS = 'BOOK_TICKET_SUCCESS';
export const BOOK_TICKET_FAILURE = 'BOOK_TICKET_FAILURE';